before_script:
  - chmod a=rwx ./scripts/travis_deploy.sh
  - apt-get install gcc-multilib g++-multilib

sudo: false
os: linux
dist: bionic

services:
  - docker

language: java

jdk:
  - openjdk13

script:
  - ./scripts/travis_deploy.sh